// ── Data ──
const INSPIRATIONS = [
  { id:'hulten', cat:'sound', title:'Love Hultén — Ferrofluid Synth Guitar',
    desc:'Modified Arturia MicroFreak in hand-built body with dancing ferrofluid visualizer, steel rod pitch control, magnetic sequencer.',
    link:'https://www.designboom.com/technology/love-hulten-guitar-synth-instrument-ferrofluid-09-22-2025/',
    img:'https://static.designboom.com/wp-content/uploads/2025/09/love-hulten-guitar-synth-instrument-ferrofluid-designboom-01.jpg',
    gallery:[
      'https://static.designboom.com/wp-content/uploads/2025/09/love-hulten-guitar-synth-instrument-ferrofluid-designboom-01.jpg',
      'https://static.designboom.com/wp-content/uploads/2025/09/love-hulten-guitar-synth-instrument-ferrofluid-designboom-02.jpg',
      'https://static.designboom.com/wp-content/uploads/2025/09/love-hulten-guitar-synth-instrument-ferrofluid-designboom-03.jpg',
      'https://static.designboom.com/wp-content/uploads/2025/09/love-hulten-guitar-synth-instrument-ferrofluid-designboom-04.jpg',
      'https://static.designboom.com/wp-content/uploads/2025/09/love-hulten-guitar-synth-instrument-ferrofluid-designboom-05.jpg',
      'https://static.designboom.com/wp-content/uploads/2025/09/love-hulten-guitar-synth-instrument-ferrofluid-designboom-06.jpg',
    ],
    videos:['https://www.youtube.com/embed/6sPbJwzi87k'],
    detail:'Swedish artist Love Hultén (Gothenburg) builds one-of-a-kind electronic instruments inside hand-crafted wooden enclosures. This piece takes an Arturia MicroFreak synth and rebuilds it into a guitar-shaped body with a ferrofluid chamber mounted in the neck. The ferrofluid reacts to magnetic fields generated by the audio signal — so you literally see the sound vibrating as dancing black spikes before you hear it. A steel rod replaces the fretboard for continuous pitch control, and a magnetic ball sequencer on the body triggers patterns. Each piece is unique, sold as art objects — typically $3K-15K range. Hultén has 200K+ Instagram followers and shows at design fairs worldwide.',
    chefTake:'This is the blueprint for "instrument as art object." The ferrofluid is pure callback/reveal — you SEE the sound before you HEAR it. That\'s temporal misdirection.\n\n🔥 For you: Imagine a Moog Muse or Push 3 session where the audio drives a ferrofluid cell filmed in macro, projected large. The instrument watches itself play. Or — generative version: a p5.js piece where particles behave like ferrofluid, reacting to an invisible "magnetic field" that the viewer discovers is actually a hidden + glyph pulling them.\n\n💡 Hultén proves there\'s a premium market for one-off sound sculptures. Your VP fabrication contacts + Moog/Ableton expertise = you could build these. The intersection of physical craft + electronic instrument + visual feedback is underexplored in the generative art world.'
  },
  { id:'vtol', cat:'kinetic', title:'::vtol:: — Kinetic Code Sculptures',
    desc:'Electronic installations reacting to environment + viewers. "Reading My Body" turns tattoos into music. Showed at Sónar+D June 2025.',
    link:'https://www.designboom.com/technology/inside-world-vtol-kinetic-sculptures-robotics-code-driven-installations-dmitry-morozov-interview-08-18-2025/',
    img:'https://static.designboom.com/wp-content/uploads/2025/08/inside-world-vtol-kinetic-sculptures-robotics-code-driven-installations-dmitry-morozov-interview-designboom-1800.jpg',
    gallery:[
      'https://static.designboom.com/wp-content/uploads/2025/08/inside-world-vtol-kinetic-sculptures-robotics-code-driven-installations-dmitry-morozov-interview-designboom-1800.jpg',
      'https://static.designboom.com/wp-content/uploads/2025/08/inside-world-vtol-kinetic-sculptures-robotics-code-driven-installations-dmitry-morozov-interview-designboom-600.jpg',
    ],
    videos:[],
    detail:'Dmitry Morozov (::vtol::) is a Moscow-born, Berlin-based artist building robotic sculptures that translate environmental data into sound and motion. "Reading My Body" uses a custom scanner to read his own tattoos as musical notation — the machine literally plays his skin. "Last Breath" is a wearable mask-organ that converts the wearer\'s breathing into pipe organ sounds. His work shown at Ars Electronica, Sónar+D (June 2025), ZKM Karlsruhe, and major new media festivals globally. He builds everything from scratch — custom PCBs, 3D-printed mechanisms, hand-soldered electronics. Open-source ethos but sells installations at institutional prices ($10K-50K+).',
    chefTake:'vtol is the anti-polish artist — raw electronics, exposed wiring, machines that look alive. The "Reading My Body" piece is a masterclass in the lens: your body IS the score, but you don\'t know it until the machine reveals it. That\'s callback.\n\n🔥 For you: The tattoo-reading concept maps directly to your + glyph work. What if a camera tracked a physical + drawn on paper, and each arm of the cross controlled a different musical parameter? The + becomes an instrument. Draw it bigger = louder. Rotate it = pitch shift. This is a TD + camera tracking piece you could prototype THIS WEEK with your existing setup.\n\n💡 He showed at Sónar+D — that\'s the deadline we\'re tracking (Feb 19). His work is exactly what they program. Your VP camera tracking chops give you an edge he doesn\'t have: real-time, sub-millimeter precision tracking that vtol does with hacky computer vision.'
  },
  { id:'eightnote', cat:'sound', title:'EightNote — Kinetic Magnetic MIDI Controller',
    desc:'MIDI.org Innovation Award 2025. Magnetic balls on a sliding 8-lane panel — rhythm as physical gesture.',
    link:'https://midi.org/innovation-award/eightnote',
    img:'https://midi.org/wp-content/uploads/2025/07/4444-1024x559.jpg',
    gallery:['https://midi.org/wp-content/uploads/2025/07/4444-1024x559.jpg'],
    videos:['https://www.youtube.com/embed/h-du-Fm8QHA'],
    detail:'EightNote won the MIDI Innovation Award 2025. It\'s a tangible MIDI controller with 8 parallel lanes — you place magnetic balls on a tilting surface and they roll along tracks, triggering MIDI notes as they cross contact points. Tilt the panel to control speed/direction. The physical movement of the balls IS the rhythm — gravity becomes your sequencer. Created by a small hardware team, open-source firmware planned. Euclidean rhythm patterns emerge naturally from the physics of rolling balls on angled surfaces. Currently in prototype stage, no retail yet.',
    chefTake:'Gravity as sequencer. This is Euclidean rhythms made physical — the balls naturally fall into patterns that mirror the mathematical distributions you\'re already exploring in Ableton.\n\n🔥 For you: Two paths here. (1) Physical: Build a version using your eurorack exploration — magnetic triggers + contact mics + a tilting surface could be a weekend prototype. (2) Digital: Recreate this in p5.js as a generative piece — simulated balls rolling on lanes, each triggering visual + audio events. The seed determines the tilt angle, so each mint produces different rhythmic patterns. This is a STRONG fxhash concept.\n\n💡 The "open-source firmware" angle means you could fork it, add Ableton Link sync, and make it talk to your Push 3. Physical instrument → digital twin → generative art. Three outputs from one concept.\n\n🕌 Islamic connection: 8 lanes = octagon = a sacred geometric form. The balls finding their pattern = tawhid (divine unity) emerging from apparent chaos.'
  },
  { id:'zimoun', cat:'kinetic', title:'Zimoun — Sound Installations',
    desc:'Hundreds of identical motors + everyday materials = emergent sonic landscapes. New commission: Staatsschauspiel Dresden 2026.',
    link:'https://zimoun.net/',
    img:'https://zimoun.net/site/assets/files/2165/2026-dresden-1.960x640.jpg',
    gallery:[
      'https://zimoun.net/site/assets/files/2165/2026-dresden-1.960x640.jpg',
      'https://zimoun.net/site/assets/files/2159/zimoun-artmuseumnantes-01.960x640.png',
      'https://zimoun.net/site/assets/files/1507/bildschirmfoto_2019-05-24_um_08_56_02.960x640.png',
      'https://zimoun.net/site/assets/files/2107/eos_r5m2_0028-k.960x640.jpg',
      'https://zimoun.net/site/assets/files/1684/zimoun-2021-191.960x640.jpg',
      'https://zimoun.net/site/assets/files/1576/zimoun-2020-1944-2644-6720x4480px.960x640.jpg',
    ],
    videos:[
      'https://player.vimeo.com/video/1158448168',
      'https://player.vimeo.com/video/1133564576',
      'https://player.vimeo.com/video/573962534',
    ],
    detail:'Zimoun (Bern, Switzerland) creates architecturally-scaled sound sculptures using hundreds of identical, simple mechanical elements: DC motors, cotton balls, cardboard boxes, wire. A single motor tapping a box = nothing. 400 motors tapping 400 boxes in a warehouse = a living, breathing organism. He\'s been doing this for 20+ years. Major institutions: MoMA, Barbican, Centre Pompidou, Art Basel. New 2026 commission at Staatsschauspiel Dresden. Also showed at Musée d\'Arts de Nantes (2025), NYU Abu Dhabi (2019), Rewire Den Haag (2025). His work is about emergence — complexity from simplicity. Budgets range from $20K gallery pieces to $200K+ architectural commissions.',
    chefTake:'Zimoun IS the concept we wrote as "Zimoun\'s Law" — one rule iterated 10,000 times. He\'s proof that the simplest possible element, repeated at scale, creates something that feels alive. The audience moment is when they realize every unit is identical.\n\n🔥 For you: This is your generative art thesis. The + glyph IS your motor. One symbol, one rule, scaled to thousands. "follow the +" is already this concept — a field of crosses that resolves into a figure. Push it further: what if you generated a Zimoun-style grid of + symbols, each slightly rotating at different speeds (like his motors), and the emergent pattern slowly reveals sacred geometry?\n\n💡 The NYU Abu Dhabi show is interesting — he\'s already in the Gulf art circuit. Your Islamic geometry angle + his emergence philosophy = a natural curatorial pairing. Worth noting for Diriyah Biennale applications.\n\n🎵 Sound angle: Record 100 instances of a single percussive hit in Ableton, offset them by random ms amounts, pan them spatially. Zimoun\'s installation as a DAW experiment. Feed it to TD for visuals.'
  },
  { id:'trimpin', cat:'sound', title:'Trimpin — The OG MIDI Sculptor',
    desc:'30+ years of electromechanical sculptures via MIDI + microcontrollers. Building-scale instruments that play themselves.',
    link:'https://en.wikipedia.org/wiki/Trimpin',
    img:'https://upload.wikimedia.org/wikipedia/commons/9/95/Trimpin_01.jpg',
    gallery:['https://upload.wikimedia.org/wikipedia/commons/9/95/Trimpin_01.jpg'],
    videos:[],
    detail:'Trimpin (born Gerhard Trimpin, Germany; based in Seattle since 1979) is a sculptor, composer, and inventor who builds massive electromechanical instruments controlled by MIDI and custom microcontrollers. His installations fill entire buildings — pianos that play themselves, guitars suspended from ceilings triggered by solenoids, percussion walls spanning 40+ feet. He received a MacArthur "Genius" Fellowship (1997). Notable works include "Klompen" (250 wooden shoes as percussion), "If VI Was IX" (Jimi Hendrix Museum guitar tower — 500+ guitars played by MIDI), and "Sheng High" (30-foot-tall glass pipe organ). He builds everything by hand, often spending years on a single piece.',
    chefTake:'Trimpin is the godfather of everything in this inspo feed. MacArthur Genius, 30+ years before anyone called it "new media." The man built a 500-guitar MIDI tower in the 90s. He proves that MIDI + physical objects + architectural scale = lasting art career.\n\n🔥 For you: Trimpin\'s work is the physical endpoint of what you\'re exploring digitally. The path: generative MIDI sequences (Ableton/Push 3) → visualize in TD → EVENTUALLY actuate physically. You don\'t need to build 500 guitars — start with one solenoid hitting one object, driven by your Euclidean sequences. Film it. That\'s a piece.\n\n💡 Career model to study: He never went commercial or mass-market. Every piece is a commission or grant-funded. MacArthur, museum commissions, university residencies. That\'s a viable path for your installation ambitions — the opposite of the NFT mint model, but they can coexist.'
  },
  { id:'transient', cat:'industry', title:'Transient Labs — Creator Platform',
    desc:'1/1s, editions, zero seller fees. Preferred minting platform for premium pieces.',
    link:'https://transient.xyz',
    img:'https://www.transient.xyz/opengraph-image.jpg?opengraph-image.30ee4b20.jpg',
    gallery:['https://www.transient.xyz/opengraph-image.jpg?opengraph-image.30ee4b20.jpg'],
    videos:[],
    detail:'Transient Labs is an Ethereum-based minting platform focused on premium digital art. Key features: zero seller fees (buyers pay gas only), support for 1/1s and editions, "Stacks" protocol for layered/evolving artworks, creator-owned smart contracts (you own your contract, not the platform), and clean collector-focused UI. Founded by artists who were frustrated with platform fees eating into creator earnings. Growing reputation among serious digital artists as the "artist-first" alternative to Foundation/SuperRare. They also built tools for synced drops, allowlists, and auction mechanics.',
    chefTake:'This is where the + triptych should live as 1/1s. Zero seller fees means you keep everything. Creator-owned contracts means if Transient Labs disappears, your art still exists on-chain.\n\n🔥 For you: The "Stacks" protocol is interesting — layered artworks that can evolve. Imagine minting the + triptych where each piece has layers that activate over time. Day 1: just the + grid. Week 1: the figure emerges. Month 1: the destruction begins. The collector watches the arc unfold in their wallet. That\'s callback/reveal applied to NFT mechanics.\n\n💡 Priority action: Set up a Transient Labs creator account. Connect your wallet. Prepare the three pieces from June 2025 at proper resolution. We can mint within a week of setting up. Don\'t overthink the first drop — these pieces are DONE.'
  },
  { id:'mori-yuko', cat:'sound', title:'Mori Yuko — Kinetic Sound Sculpture',
    desc:'Ghost orchestra — accordion, bass drum, megaphone, bells all connected by cable networks running solenoids. Calder Prize winner.',
    link:'https://x.com/najapan/status/2019821250030514278',
    img:'https://frieze.com/sites/default/files/styles/hero_image/public/yuko-mohri-kinetic-installation.jpg',
    gallery:['https://frieze.com/sites/default/files/styles/hero_image/public/yuko-mohri-kinetic-installation.jpg','https://glasgowinternational.org/wp-content/uploads/yuko-mohri-gi2024.jpg','https://sculpturemagazine.art/wp-content/uploads/2024/11/yuko-mohri-circulating.jpg'],
    videos:[],
    detail:'Mori Yuko (毛利悠子) is a Calder Prize-winning Japanese artist whose kinetic sound sculptures create "ghost orchestras" — automated instruments playing themselves on stark white platforms. Her exhibition "セカイノコトワリ" (The Logic of the World) at Kyoto National Museum of Modern Art features accordions, bass drums, megaphones, wire sculptures, and bells all connected by black cable networks running solenoids and motors.\n\nNo human performers. Objects play themselves. The stark white gallery backdrop against dark wire networks creates what looks like 3D drawing in space — the cables become lines, the instruments become nodes in a physical generative system.',
    chefTake:'🔥 For you: This IS your MIDI-controlled solenoid/actuator project at museum scale. Study Mori Yuko\'s approach: Ableton/Push → MIDI → Arduino/Teensy → solenoids/motors → physical objects. She\'s already proven the gallery path. Your advantage: you can add the generative layer (TouchDesigner driving the MIDI patterns algorithmically) that she does manually.\n\n💡 The "ghost orchestra" concept is incredibly powerful. Imagine a version where your + glyph is drawn in cable routing — the network of wires between instruments forms the symbol when viewed from above. The music plays, and only from a specific vantage point do you see the hidden pattern. Callback/reveal in physical installation.\n\n🕌 The call to prayer (adhan) is a sonic architecture that fills physical space. A kinetic sound sculpture that performs algorithmic variations on the adhan\'s melodic structure — using solenoids on bells, strings, and resonant objects — would be a profound intersection of your technical and spiritual practice.'
  },
  { id:'fendoap-midi', cat:'sound', title:'Fendoap — MIDI Notes Choreography',
    desc:'Visual MIDI choreography — note data controlling movement/animation. Amplified by Ableton\'s official account.',
    link:'https://x.com/seitokisoukari/status/2018700088239915407',
    img:'https://f4.bcbits.com/img/0025814513_10.jpg',
    gallery:['https://f4.bcbits.com/img/0025814513_10.jpg'],
    videos:[],
    detail:'Fendoap (Yusuie ao, @seitokisoukari) is a Japanese Max for Live developer whose visual MIDI choreography work was impressive enough for Ableton\'s official account to amplify. The piece visualizes MIDI note data as movement and animation — notes become dancers, velocity becomes force, timing becomes rhythm in visual space.\n\nThe work bridges the Japanese generative music community and the global Ableton ecosystem. Fendoap builds Max for Live devices that transform MIDI data into visual output — the same pipeline Tawfeeq is building with Ableton → TouchDesigner.',
    chefTake:'🔥 For you: Fendoap\'s MIDI-as-choreography concept maps directly to your pipeline. Ableton/Push 3 generates MIDI → Max for Live or VOID bridge sends to TouchDesigner → visuals dance with the music. But take it further: MIDI → physical actuators (solenoids) → objects choreographed by your playing. Digital choreography becomes physical choreography.\n\n💡 Monitor Fendoap for Max for Live tools — they\'re building exactly the MIDI visualization devices you need. The Japanese M4L community is small but incredibly skilled. Fendoap, Cycling \'74 Japan, and the Ableton Tokyo meetup scene are all worth connecting with.\n\n🕌 Choreography from unseen data — movement that appears spontaneous but follows hidden rules — is a beautiful metaphor for qadr (divine decree). Things appear random but follow a deeper pattern. A piece that reveals the MIDI data driving the dance only at the end = callback/reveal of the hidden order.'
  },
  { id:'underwater-caustics', cat:'light', title:'Underwater Caustics Light Installation',
    desc:'Projected light creates underwater illusion — caustic patterns rippling across walls and ceiling of a room.',
    link:'https://x.com/sciencegirl/status/2021817986815078685',
    img:'kitchen-img/caustics.jpg',
    gallery:['kitchen-img/caustics.jpg'],
    videos:['kitchen-img/caustics.mp4'],
    detail:'A projected light installation that creates the illusion of being underwater — caustic light patterns ripple across the walls and ceiling of a room. The effect simulates water refraction patterns (caustics) using projection mapping, transforming an ordinary space into a submerged environment.\n\nCaustic simulation is a well-understood shader technique (ray tracing water surface → projecting refracted light patterns). The magic is in the scale — filling an entire room with the effect creates full environmental immersion. The technique can be done in real-time with Unreal Engine or TouchDesigner.',
    chefTake:'🔥 For you: This is RIGHT in your VP wheelhouse. Caustic light simulation is a standard Unreal/TD shader — you could build this in an afternoon. But the art is in the application: project it in a gallery, a mosque, a warehouse. The room becomes the canvas. Imagine a version where the caustic patterns slowly resolve into + glyphs — water revealing hidden geometry.\n\n💡 Projection mapping + environmental illusion is one of the most accessible installation formats. Projector ($500-2K) + computer + shader = immersive experience. Low barrier, high impact. This could be your first physical installation — test it in your own space, document it, submit to open calls.\n\n🕌 Water is sacred in Islam — wudu (ablution), the rivers of Jannah, "We made from water every living thing" (21:30). A caustic light installation in a prayer space would be deeply moving. The light patterns ARE water — purification through light.'
  },
  { id:'butterflies-light', cat:'light', title:'Dancing Butterflies of Light',
    desc:'Light installation — projected or kinetic butterflies made of light. Immersive environmental illusion.',
    link:'https://x.com/BiancoDavinci/status/2022021368867643443',
    img:'kitchen-img/butterflies.jpg',
    gallery:['kitchen-img/butterflies.jpg'],
    videos:['kitchen-img/butterflies.mp4'],
    detail:'A light installation featuring dancing butterflies made entirely of projected or kinetic light, captured in a 13-second vertical video. The butterflies appear to flutter through physical space, creating an immersive environmental illusion that blurs the boundary between digital projection and physical reality.\n\nThis pairs with the underwater caustics piece as part of a clear pattern in Tawfeeq\'s bookmarks: immersive projected light installations that transform spaces through illusion. Light as medium, space as canvas.',
    chefTake:'🔥 For you: Another confirmation that projected light installations are your entry point to physical art. Butterflies as particle systems — each one a sprite with flocking behavior, projected into a room. TouchDesigner particle system → projector → magic. You could build a version where + glyphs behave like butterflies — flocking, landing, resting on surfaces.\n\n💡 The vertical video format (9:16) matters — this went viral because it\'s native to phone viewing. When you document your installations, shoot vertical. The installation lives twice: once in the room, once on social media. Design for both.\n\n🕌 Butterflies represent transformation (metamorphosis) across cultures. In Islamic tradition, the beauty of creation reflects divine artistry. A light installation where butterflies emerge from calligraphic forms — the letter becomes the wing — would bridge the aesthetic and spiritual beautifully.'
  },
  { id:'delahunty-pcb', cat:'generative', title:'David Delahunty — Paint Stripper (PCB Art)',
    desc:'Conceptual design — paint scraper with PCB blade, shot as serious product catalog. Object-based surrealism.',
    link:'https://x.com/Delahuntagram/status/2019984534255583694',
    img:'https://freight.cargo.site/w/1000/i/L2789878882833963638909747836180/screenshot-3089711113.jpg',
    gallery:['https://freight.cargo.site/w/1000/i/L2789878882833963638909747836180/screenshot-3089711113.jpg'],
    videos:[],
    detail:'David Delahunty (@Delahuntagram) is a Dublin-based conceptual designer known as "your favorite designer\'s favorite designer" (25K followers). "Paint Stripper" is a conceptual piece — a paint scraper with a PCB (printed circuit board) as its blade, photographed as a serious product catalog item with straight-faced spec text.\n\nThe comedy comes from misplaced context: a circuit board doing manual labor, technology reduced to a hand tool. Object-based surrealism meets product design meets deadpan humor. Clean, minimal, editorial aesthetic — Duchamp readymade energy with graphic design polish.',
    chefTake:'🔥 For you: The deadpan sincerity is the lesson here. Take a technical object (GPU, MIDI controller, circuit board) and present it in a completely wrong context with total seriousness. A PCB framed as Islamic geometric tilework. A GPU heatsink presented as architectural model. The + glyph etched into silicon and displayed as archaeological artifact. The humor comes from the gap between presentation and reality.\n\n💡 This aesthetic — clean product photography of absurd objects — translates beautifully to NFT presentation. The thumbnail looks "normal" until you read the description and realize what you\'re seeing. Callback/reveal in still image form. Could be a whole 1/1 series on Transient Labs.\n\n🕌 Islamic calligraphy has always played with context — the same word can be an inscription on a mosque, a piece of jewelry, a sword blade. Sacred text in mundane contexts (and vice versa) is a centuries-old tradition. Delahunty\'s approach is the secular version of that same game.'
  },
  { id:'beyer-nature-tech', cat:'kinetic', title:'Hank Beyer — Nature Reclaiming Tech',
    desc:'Computer monitor buried in soil with plants growing from it. Post-digital futurism — earth reclaiming screens.',
    link:'https://x.com/blankspac_e/status/2019071776559669340',
    img:'https://www.ignant.com/wp-content/uploads/2017/11/ignant-design-hank-beyer-caravanserai-005.jpg',
    gallery:['https://www.ignant.com/wp-content/uploads/2017/11/ignant-design-hank-beyer-caravanserai-005.jpg'],
    videos:[],
    detail:'Hank Beyer & Alex Sizemore created a sculptural installation — a computer monitor buried in soil with plants growing from the screen. Cables connect to soil patches shaped like a keyboard and mouse, each sprouting greenery. Shot in Apple product photography style against white.\n\nThe work asks: what comes after the screen age? Nature × technology tension rendered as post-digital futurism. The Apple-clean aesthetic applied to organic decay creates a cognitive dissonance that lingers.',
    chefTake:'🔥 For you: The nature × technology tension is rich territory for generative art. A piece where + glyphs slowly get overgrown by procedural vegetation — L-system plants consuming geometric forms. Time-based: the longer the piece runs, the more nature reclaims the grid. Could be a Transient Labs "Stacks" piece where the artwork evolves over weeks.\n\n💡 The product photography aesthetic is key — presenting the absurd with total seriousness elevates it from "craft project" to "art." When you photograph/render your physical pieces, use this Apple-catalog language. Clean background, perfect lighting, the object speaks for itself.\n\n🕌 "From the earth We created you, and into it We will return you" (20:55). Nature reclaiming technology is literally a visualization of this verse. The screen returns to soil. A generative version — digital geometry dissolving into organic forms — would carry that resonance.'
  },
  { id:'puyoma-eurorack', cat:'sound', title:'Puyoma — Eurorack AV System',
    desc:'Compact Make Noise-centric 2-row eurorack. QPAS, Mimeophon, Data Bender, Beads. Effects-heavy AV rig from Osaka.',
    link:'https://x.com/puyoma99/status/2016136693062287686',
    img:'data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20width=%22400%22%20height=%22300%22%3E%3Cdefs%3E%3ClinearGradient%20id=%22g%22%20x1=%220%22%20y1=%220%22%20x2=%221%22%20y2=%221%22%3E%3Cstop%20offset=%220%25%22%20stop-color=%22%23111118%22/%3E%3Cstop%20offset=%22100%25%22%20stop-color=%22%230e0e14%22/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect%20fill=%22url(%23g)%22%20width=%22400%22%20height=%22300%22/%3E%3C/svg%3E',
    gallery:[],
    videos:[],
    detail:'Puyoma (@puyoma99) is an Osaka-based audiovisual/experimental electronics artist. Their eurorack system is a compact 2-row setup centered on Make Noise modules: QPAS → Mimeophon → 2× Data Bender → Beads + power (top row), MultiMod → MultiWave → PaliMATHS → 2× AXG (bottom row).\n\nThe system is effects-heavy and texture-focused, designed for AV performance rather than traditional composition. The Make Noise ecosystem is cohesive — modules designed to work together, creating a unified sonic palette ideal for pairing with real-time visuals.',
    chefTake:'🔥 For you: This is your eurorack starting reference. Puyoma\'s system is minimal but complete — effects-heavy, texture-focused, AV-ready. With your Moog Muse as the primary synth voice, a small eurorack effects chain like this would add the textural complexity and happy accidents that make live AV compelling. QPAS (filter) → Mimeophon (delay/loop) → Data Bender (glitch) is a murderous signal chain.\n\n💡 The Make Noise ecosystem is the right starting point — designed for exploration, well-documented, great community. Start with 2-3 modules that complement the Muse rather than replace it. Budget: $1.5-2K for a starter rack including case. The ROI is in the unique textures you can\'t get from software alone.\n\n🕌 Modular synthesis as spiritual practice: the patch is a prayer — you build it, you submit to the signal flow, and what emerges is partly your intention and partly the system\'s nature. Tawakkul (trust in God\'s plan) expressed through voltage.'
  },
  { id:'takao-immersive', cat:'light', title:'Kodai Takao — Immersive Experience Specialist',
    desc:'Japanese immersive experience designer. Large-scale light + projection installations bridging technology and wonder.',
    link:'https://x.com/kodai_takao',
    img:'https://stu.inc/assets/meta/ogp.jpg',
    gallery:['https://stu.inc/assets/meta/ogp.jpg'],
    videos:[],
    detail:'Kodai Takao is a Japanese immersive experience specialist working at the intersection of projection mapping, light design, and interactive installation. Based in Tokyo, he creates large-scale environmental experiences that transform physical spaces through technology.\n\nHis work represents the Japanese approach to immersive art — meticulous attention to detail, seamless integration of technology into space, and an emphasis on wonder over spectacle. Japan\'s immersive art scene (teamLab, NAKED, Rhizomatiks) is the most advanced in the world, and Takao operates in that ecosystem.',
    chefTake:'🔥 For you: Japan is the global leader in immersive light installations. Takao and the broader Tokyo scene (teamLab, Rhizomatiks, NAKED) represent where this medium is going. Your VP experience at ILM maps directly to immersive installation — same tools (LED, projection, real-time rendering), different context (gallery instead of soundstage).\n\n💡 If you visit Tokyo (or when the next industry trip comes up), the immersive art scene is a must-see. teamLab Borderless, NAKED exhibitions, and smaller gallery shows. These aren\'t just inspiration — they\'re market research for your own installation practice.\n\n🕌 Japanese aesthetic concepts like "ma" (negative space) and "wabi-sabi" (beauty in imperfection) have deep parallels with Islamic art principles. Both traditions value what\'s NOT shown as much as what is. A collaboration between Japanese immersive technique and Islamic geometric content would be genuinely groundbreaking.'
  },
  { id:'mark-fell-multistability', cat:'sound', title:'Mark Fell — Multistability',
    desc:'Generative electronic music using algorithmic processes, exploring how pattern recognition creates rhythm from non-repeating sequences.',
    link:'https://markfell.com/',
    img:'https://markfell.com/images/mark-fell-multistability.jpg',
    gallery:['https://markfell.com/images/mark-fell-multistability.jpg'],
    videos:[],
    detail:'Mark Fell makes electronic music that sits at the edge of pattern recognition. His Multistability album uses algorithmic processes to generate sequences that almost repeat but never quite do — your brain constantly predicts the next beat and is constantly slightly wrong.\n\nFell\'s theoretical framework draws from cognitive science and cybernetics. He is interested in the moment where the listener\'s pattern-matching machinery kicks in and imposes structure on what is actually non-repeating.',
    chefTake:'🔥 For you: Fell\'s "almost-repeating" approach is the audio equivalent of your callback/reveal. Program Euclidean rhythms on Push 3 that shift by one step every 17 bars. The audience feels the groove, then feels it drift, then snaps back. The + glyph as temporal structure.\n\n💡 His academic approach to electronic music gives it gallery credibility. Your work can bridge club and gallery the same way — Ableton for the groove, TD for the visual theory.\n\n🕌 Islamic pattern work uses similar near-repetition — the same motif slightly rotated creates infinite variety from finite rules.'
  }
];

const CONCEPTS = [
  { title:'The Callback Machine', body:'Islamic geometric patterns generated by one rule repeated. Generative piece starts as chaos, reveals the single rotation underneath. Perceptual one-way door applied to sacred geometry.' },
  { title:'The Instrument That Watches You Back', body:'Camera tracking watching a performer\'s body tension/breath/posture. Instrument reacts: softens when anxious, pushes back when confident. Not AI — reactive physics. Duet discovered.' },
  { title:'Zimoun\'s Law', body:'One motor + one cotton ball = boring. 139 = living organism. Your art needs ONE elegant rule iterated 10,000 times. Beauty is in the moment the audience realizes the rule.' },
  { title:'The Muezzin\'s Delay', body:'Adhan cascades across cities as each muezzin starts moments apart. Spatial canon written by architecture. Sound installation with speakers at cascading distances. The room becomes the instrument.' },
  { title:'Tattoo Machine Score', body:'Generative system creates visual score, robotic arm draws it as ink in real-time. Paper = record. Drawing IS the music frozen. Frame it. Play it back with a camera.' },
  { title:'The Prayer Rug Sequencer', body:'Prayer rug geometric patterns as step sequencer grid. Conductive thread at intersections = trigger points. Sacred geometry literally becomes music. The math that made these patterns = Euclidean rhythms.' },
  { title:'Crown Shyness Code', body:'Particles grow and fill space but never overlap. Run it long enough and it looks like Islamic geometric patterns. Nature and sacred geometry share a codebase.' },
  { title:'The Ferrofluid Qibla', body:'Ferrofluid cell with hidden magnet toward Mecca. Fluid perpetually reaches one direction. Visitors don\'t know why until the label. Liquid compass performing devotion.' },
];

const DEADLINES = [
  { emoji:'', name:'Ramadan begins', date:new Date('2026-02-17'), color:'var(--purple)' },
  { emoji:'', name:'Sónar+D Barcelona', date:new Date('2026-02-19'), color:'var(--red)' },
  { emoji:'', name:'Hasselblad Masters', date:new Date('2026-02-28'), color:'var(--amber)' },
  { emoji:'', name:'Art Blocks Marfa RSVP', date:new Date('2026-03-15'), color:'var(--emerald)' },
];

const STARTER_SKETCH = `function setup() {
  createCanvas(windowWidth, windowHeight);
  background(10);
  textAlign(CENTER, CENTER);
  textFont('monospace');
  noLoop();
}

function draw() {
  background(10, 10, 11);
  let size = 12;
  let cols = floor(width / size);
  let rows = floor(height / size);
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < cols; x++) {
      let n = noise(x * 0.05, y * 0.05);
      if (n > 0.45) {
        let brightness = map(n, 0.45, 1, 50, 255);
        fill(brightness);
        noStroke();
        text('+', x * size + size/2, y * size + size/2);
      }
    }
  }
}

function mousePressed() {
  noiseSeed(random(10000));
  redraw();
}`;

const TECHNIQUES = [
  { name:'Perlin Noise Flow Field', cat:'noise', desc:'Particles follow invisible vector fields created by noise functions', code:`let particles = [];
function setup() {
  createCanvas(windowWidth, windowHeight);
  background(10, 10, 11);
  for (let i = 0; i < 800; i++) particles.push(createVector(random(width), random(height)));
  textAlign(CENTER, CENTER); textFont('monospace');
}
function draw() {
  fill(10, 10, 11, 15); noStroke(); rect(0, 0, width, height);
  let t = frameCount * 0.002;
  for (let p of particles) {
    let a = noise(p.x * 0.003, p.y * 0.003, t) * TWO_PI * 2;
    p.x += cos(a) * 1.5; p.y += sin(a) * 1.5;
    let b = map(noise(p.x*0.005, p.y*0.005), 0, 1, 60, 255);
    fill(b); textSize(10); text('+', p.x, p.y);
    if (p.x < 0 || p.x > width || p.y < 0 || p.y > height) {
      p.x = random(width); p.y = random(height);
    }
  }
}` },
  { name:'L-Systems', cat:'growth', desc:'Recursive string-rewriting rules that generate organic branching structures', code:`let sentence, rules, angle, len;
function setup() {
  createCanvas(windowWidth, windowHeight);
  background(10, 10, 11);
  angle = radians(25); len = max(height * 0.22, 60);
  sentence = 'F'; rules = [{a:'F', b:'FF+[+F-F-F]-[-F+F+F]'}];
  for (let i = 0; i < 4; i++) generate();
  drawTree();
}
function generate() {
  let next = '';
  for (let c of sentence) {
    let found = rules.find(r => r.a === c);
    next += found ? found.b : c;
  }
  sentence = next;
}
function drawTree() {
  background(10, 10, 11);
  stroke(80, 200, 120); strokeWeight(1); noFill();
  resetMatrix(); translate(width/2, height);
  let l = len * pow(0.5, 4);
  for (let c of sentence) {
    if (c === 'F') { line(0,0,0,-l); translate(0,-l); }
    else if (c === '+') rotate(angle);
    else if (c === '-') rotate(-angle);
    else if (c === '[') push();
    else if (c === ']') pop();
  }
}
function mousePressed() { noiseSeed(random(10000)); angle = radians(random(15,35)); sentence='F'; for(let i=0;i<4;i++) generate(); drawTree(); }` },
  { name:"Conway's Game of Life", cat:'cellular', desc:'Simple birth/death rules on a grid produce emergent complexity', code:`let grid, cols, rows, sz = 10;
function setup() {
  createCanvas(windowWidth, windowHeight);
  textAlign(CENTER, CENTER); textFont('monospace'); textSize(sz);
  cols = floor(width/sz); rows = floor(height/sz);
  grid = Array.from({length:cols}, ()=>Array.from({length:rows}, ()=>random()>.7?1:0));
}
function draw() {
  background(10, 10, 11);
  fill(168, 85, 247);
  for (let x=0; x<cols; x++) for (let y=0; y<rows; y++) {
    if (grid[x][y]) text('+', x*sz+sz/2, y*sz+sz/2);
  }
  let next = Array.from({length:cols}, ()=>Array(rows).fill(0));
  for (let x=0; x<cols; x++) for (let y=0; y<rows; y++) {
    let s = 0;
    for (let dx=-1; dx<=1; dx++) for (let dy=-1; dy<=1; dy++) {
      if (dx===0&&dy===0) continue;
      let nx=(x+dx+cols)%cols, ny=(y+dy+rows)%rows;
      s += grid[nx][ny];
    }
    if (grid[x][y]) next[x][y] = (s===2||s===3)?1:0;
    else next[x][y] = s===3?1:0;
  }
  grid = next;
}` },
  { name:'Voronoi Tessellation', cat:'geometry', desc:"Space partitioned by nearest-neighbor distance — nature's tiling algorithm", code:`let pts = [];
function setup() {
  createCanvas(windowWidth, windowHeight);
  for (let i = 0; i < 30; i++) pts.push({x:random(width),y:random(height),vx:random(-0.5,0.5),vy:random(-0.5,0.5)});
  noStroke(); textAlign(CENTER,CENTER); textFont('monospace');
}
function draw() {
  background(10,10,11);
  let step = 8;
  for (let px=0; px<width; px+=step) for (let py=0; py<height; py+=step) {
    let minD=Infinity, ci=0;
    for (let i=0;i<pts.length;i++) {
      let d=dist(px,py,pts[i].x,pts[i].y);
      if (d<minD){minD=d; ci=i;}
    }
    let h = (ci*37)%360;
    fill(h,40,max(20,70-minD*0.15));
    textSize(step); text('+', px, py);
  }
  for (let p of pts) {
    p.x+=p.vx; p.y+=p.vy;
    if(p.x<0||p.x>width) p.vx*=-1;
    if(p.y<0||p.y>height) p.vy*=-1;
  }
}` },
  { name:'Circle Packing', cat:'geometry', desc:'Fill space with non-overlapping circles — crown shyness in 2D', code:`let circles = [];
function setup() {
  createCanvas(windowWidth, windowHeight);
  background(10,10,11);
  textAlign(CENTER,CENTER); textFont('monospace');
}
function draw() {
  background(10,10,11);
  for (let i = 0; i < 10; i++) {
    let c = {x:random(width),y:random(height),r:2,growing:true};
    let ok = true;
    for (let o of circles) if (dist(c.x,c.y,o.x,o.y)<o.r+c.r+2) { ok=false; break; }
    if (ok && circles.length < 500) circles.push(c);
  }
  for (let c of circles) {
    if (!c.growing) continue;
    c.r += 0.4;
    if (c.x-c.r<0||c.x+c.r>width||c.y-c.r<0||c.y+c.r>height) { c.growing=false; continue; }
    for (let o of circles) {
      if (o===c) continue;
      if (dist(c.x,c.y,o.x,o.y)<c.r+o.r+2) { c.growing=false; break; }
    }
  }
  noStroke();
  for (let c of circles) {
    let b = map(c.r, 2, 80, 40, 220);
    fill(b); textSize(max(6, c.r*0.6));
    let n = max(1, floor(c.r/6));
    for (let j=0; j<n; j++) {
      let a=j*(TWO_PI/n), d=c.r*0.5;
      text('+', c.x+cos(a)*d, c.y+sin(a)*d);
    }
  }
}` },
  { name:'Diffusion Limited Aggregation', cat:'growth', desc:'Random walkers that stick on contact — grows coral, lightning, and city maps', code:`let tree, walkers;
function setup() {
  createCanvas(windowWidth, windowHeight);
  background(10,10,11);
  textAlign(CENTER,CENTER); textFont('monospace'); textSize(6);
  tree = [{x:floor(width/2),y:floor(height/2)}];
  walkers = [];
  for (let i=0;i<200;i++) walkers.push(rndEdge());
  noLoop();
}
function rndEdge() {
  let s=floor(random(4));
  if(s===0) return {x:random(width),y:0};
  if(s===1) return {x:width,y:random(height)};
  if(s===2) return {x:random(width),y:height};
  return {x:0,y:random(height)};
}
function draw() {
  for (let step=0;step<2000;step++) {
    for (let i=walkers.length-1;i>=0;i--) {
      let w=walkers[i];
      w.x+=random(-3,3); w.y+=random(-3,3);
      let stuck=false;
      for (let t of tree) if (dist(w.x,w.y,t.x,t.y)<5) { stuck=true; break; }
      if (stuck) { tree.push(w); walkers.splice(i,1); walkers.push(rndEdge()); }
    }
  }
  background(10,10,11);
  for (let i=0;i<tree.length;i++) {
    let b=map(i,0,tree.length,50,220);
    fill(16,b,129); text('+',tree[i].x,tree[i].y);
  }
  if (tree.length < 1500) redraw();
}` },
  { name:'Boids / Flocking', cat:'physics', desc:'Three simple rules (separate, align, cohere) produce lifelike swarm behavior', code:`let boids = [];
function setup() {
  createCanvas(windowWidth, windowHeight);
  for (let i=0; i<150; i++) boids.push({
    x:random(width),y:random(height),vx:random(-2,2),vy:random(-2,2)
  });
  textAlign(CENTER,CENTER); textFont('monospace');
}
function draw() {
  background(10,10,11,40);
  for (let b of boids) {
    let sx=0,sy=0,ax=0,ay=0,cx=0,cy=0,sc=0,ac=0,cc=0;
    for (let o of boids) {
      if(o===b) continue;
      let d=dist(b.x,b.y,o.x,o.y);
      if(d<20){sx+=b.x-o.x;sy+=b.y-o.y;sc++;}
      if(d<50){ax+=o.vx;ay+=o.vy;ac++;}
      if(d<80){cx+=o.x;cy+=o.y;cc++;}
    }
    if(sc){b.vx+=sx/sc*0.05;b.vy+=sy/sc*0.05;}
    if(ac){b.vx+=(ax/ac-b.vx)*0.05;b.vy+=(ay/ac-b.vy)*0.05;}
    if(cc){b.vx+=(cx/cc-b.x)*0.001;b.vy+=(cy/cc-b.y)*0.001;}
    let spd=sqrt(b.vx*b.vx+b.vy*b.vy);
    if(spd>3){b.vx=b.vx/spd*3;b.vy=b.vy/spd*3;}
    b.x+=b.vx; b.y+=b.vy;
    if(b.x<0)b.x=width; if(b.x>width)b.x=0;
    if(b.y<0)b.y=height; if(b.y>height)b.y=0;
    fill(6,182,212); textSize(10); text('+',b.x,b.y);
  }
}` },
  { name:'Islamic Star Patterns (Girih)', cat:'geometry', desc:'One rotation rule reflected and repeated fills an infinite plane', code:`function setup() {
  createCanvas(windowWidth, windowHeight);
  background(10,10,11);
  noFill(); stroke(245,158,11,180); strokeWeight(1);
  let s = 60, cols = ceil(width/s)+1, rows = ceil(height/(s*0.866))+1;
  for (let row=0; row<rows; row++) for (let col=0; col<cols; col++) {
    let cx = col*s + (row%2)*s/2, cy = row*s*0.866;
    drawStar(cx, cy, s*0.45, 8);
  }
  noLoop();
}
function drawStar(cx, cy, r, points) {
  let inner = r * 0.4;
  beginShape();
  for (let i=0; i<points*2; i++) {
    let a = i*PI/points - HALF_PI;
    let rad = i%2===0 ? r : inner;
    vertex(cx+cos(a)*rad, cy+sin(a)*rad);
  }
  endShape(CLOSE);
  for (let i=0; i<points; i++) {
    let a = i*TWO_PI/points - HALF_PI;
    line(cx+cos(a)*inner, cy+sin(a)*inner, cx+cos(a+PI/points)*inner, cy+sin(a+PI/points)*inner);
  }
}
function mousePressed() { background(10,10,11); let s=random(40,80); let pts=floor(random(5,12)); let cols=ceil(width/s)+1, rows=ceil(height/(s*0.866))+1; noFill(); stroke(245,158,11,180); for(let r=0;r<rows;r++) for(let c=0;c<cols;c++){let cx=c*s+(r%2)*s/2,cy=r*s*0.866; drawStar(cx,cy,s*0.45,pts);} }` },
  { name:'Survivor Bias Visualization', cat:'data', desc:"What you don't see defines the pattern — the missing data tells the story", code:`let dots = [];
function setup() {
  createCanvas(windowWidth, windowHeight);
  textAlign(CENTER,CENTER); textFont('monospace');
  for (let i=0;i<500;i++) dots.push({
    x:random(width),y:random(height),alive:true,
    strength:random(1),fade:255
  });
}
function draw() {
  background(10,10,11);
  let cx=width/2,cy=height/2,maxD=dist(0,0,cx,cy);
  for (let d of dots) {
    if (!d.alive) { d.fade = max(0, d.fade-2); }
    else {
      let dd = dist(d.x,d.y,cx,cy)/maxD;
      if (random() < dd*0.02 && d.strength < dd) d.alive = false;
    }
    if (d.fade > 0) {
      let c = d.alive ? [107,114,128] : [239,68,68];
      fill(c[0],c[1],c[2], d.fade * (d.alive?1:0.4));
      textSize(d.alive ? 10 : 8);
      text('+', d.x, d.y);
    }
  }
  fill(255,60); textSize(11);
  text('survivors cluster at center — selection bias revealed', width/2, 24);
}` },
  { name:'Domain Warping', cat:'noise', desc:'Feed noise into noise — simple recursion creates alien organic landscapes', code:`function setup() {
  createCanvas(windowWidth, windowHeight);
  pixelDensity(1); noLoop();
}
function draw() {
  loadPixels();
  let s = 0.004, t = millis()*0.0001;
  for (let y=0; y<height; y++) for (let x=0; x<width; x++) {
    let qx = noise(x*s, y*s, t);
    let qy = noise(x*s+5.2, y*s+1.3, t);
    let rx = noise((x+qx*80)*s, (y+qy*80)*s, t+1.7);
    let ry = noise((x+qx*80)*s+9.2, (y+qy*80)*s+3.4, t+2.1);
    let v = noise((x+rx*80)*s, (y+ry*80)*s, t);
    let i = (y*width+x)*4;
    pixels[i] = v*20; pixels[i+1] = v*100+40; pixels[i+2] = v*180+50; pixels[i+3] = 255;
  }
  updatePixels();
}
function mousePressed() { noiseSeed(random(10000)); redraw(); }` },
];

// ── Helpers ──